image: docker:19

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - docker version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - develop

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - curl -XPOST $WWW_WEBHOO
  only:
    - develop
