module.exports = {
    CONFIG: {
        CONDITION: {
            EXPIRED: 20,
            NAP: 0,
            SPEND: 0
        }
    },
    ERROR_PAGE: {
        NOT_FOUND: 'Trang này không tồn tại',
    },
    ERROR_FORM: {
        MISSING_FIELD: 'Giá trị trường đầu vào bị thiếu',
        MISSING_PAGE: 'Thiếu giá trị trang',
        MISSING_NICKNAME: 'Vui lòng nhập tên nhân vật của bạn'
    },
    ERROR_AUTH: {
        TOKEN_INVALID: 'Mã thông báo truy cập không hợp lệ!',
        NO_ACCESS: 'Không được phép truy cập tài nguyên này!',
        LOGIN_FAIL: 'Tài khoản hoặc mật khẩu không chính xác!',
        NOT_FOUND_REFERER_CODE: 'Không tìm thấy mã đại lý!',
        PASSWORD_INVALID: 'Mật khẩu không đúng!',
        RequestPasswordReset: 'Yêu cầu đặt lại mật khẩu!',
    },
    ERROR_AGENT: {
        AGENT_NOT_FOUND: 'Đại lý không tồn tại!',
        AGENT_CANT_CREATE: "Không thể tạo đại lý!",
        AGENT_USERNAME_SAME_AS_ORTHER_AGENT: "Tên người dùng đã giống với tên người khác!",
        AGENT_USERNAME_MUST_OTHER_PASSWORD: "Tài khoản không thể khớp với mật khẩu!",
        AGENT_NAME_LESS_THAN: "Tên đại lý (3-32 ký tự).",
        AGENT_USERNAME_LESS_THAN: "Tên đại lý (3-32 ký tự).",
        AGENT_NAME_MUST_BE_STRING_OR_NUMBER: "Tên đại lý chỉ bao gồm các chữ cái và số!!",
        AGENT_USERNAME_MUST_BE_STRING_OR_NUMBER: "Tên người dùng của đại lý chỉ bao gồm các chữ cái và số!!",
        AGENT_REFERER_CODE_LESS_THAN: "Mã giới thiệu (3-32 ký tự).",
        AGENT_REFERER_CODE_MUST_BE_STRING_OR_NUMBER: "Mã giới thiệu chỉ bao gồm chữ cái và số!!",
        AGENT_REFERER_CODE_MUST_BE_ORTHER_PLAYER_NICKNAME: "Mã giới thiệu phải khác với tên người chơi!"
    },
    SUCCESS_PROCEDURE_RESPONSE_CODE: 1,
    UPDATE_SUCCESS_RESPONSE_TEXT: "Cập nhật thành công!",
    INSERT_SUCCESS_RESPONSE_TEXT: "Thêm mới thành công!",
    UPDATE_FAIL_RESPONSE_TEXT: "Cập nhật không thành công. Vui lòng thử lại sau!",
    ERROR_AUTH_MESSAGE: {
        AccessDenied: "Tài nguyên này không được phép!",
        InvalidName: "Họ và tên không hợp lệ",
        InvalidUsername: "Tên tài khoản không hợp lệ",
        InvalidField: "Tên tài khoản không hợp lệ",
        InvalidEmail: "Email không hợp lệ",
        InvalidPasswordShort: "Mật khẩu quá ngắn",
        InvalidPasswordNotMatch: "2 mật khẩu không giống nhau",
        UsernameExists: "Tên người dùng này đã được đăng ký cho người dùng khác",
        EmailExists: "Email này đã được đăng ký với người dùng khác",
        NotVerify: "Tài khoản của bạn không hợp lệ",
        InvalidCode: "Mã xác minh không hợp lệ",
        AccountHasVerify: "Tài khoản này đã được xác minh",
        InvalidReferer: "Người giới thiệu không hợp lệ",
        MissingFieldList: "Vui lòng nhập đầy đủ thông tin",
        ErrorParams: "Thông số lỗi",
        InvalidRefcode: "Mã đại lý không hợp lệ!",
        AgencyNotFound: "Không tìm thấy đại lý với mã",
    },
    ERROR_CODES: {
        InvalidLoginCredentials: "Thất bại",
        InvalidOrExpiredToken: "Token không hợp lệ hoặc đã hết hạn",
        AccessDenied: "Từ chối truy cập",
        NeedActive: "Tài khoản cần được xác minh",
        NeedVerify: "Tài khoản chưa được xác minh",
        SomeErrorsOccurredPleaseTryAgain: "Có lỗi xảy ra. Vui lòng thử lại",
        NoPermissionToAccessThisResource: "Không có quyền truy cập tài nguyên này",
        AccountBlocked: "Tài khoản đã bị khóa",
        AccountNotFound: "Account not found",
        InvalidVerifyCode: "Mã xác minh không hợp lệ",
        PhoneNotFound: "Không tìm thấy tài khoản nào có số điện thoại này",
        CaptchaInvalid: "Hình ảnh xác thực không hợp lệ."
    },
    ERROR_MESSAGES: {
        MissingFieldList: "Vui lòng nhập đầy đủ thông tin",
        ErrorTaskName: "Tên không hợp lệ",
        ErrorNameLength: "Độ dài của họ và tên phải lớn hơn 8 và nhỏ hơn 50 ký tự",
        ErrorUsernameLength: "Độ dài tên người dùng phải lớn hơn 5 và nhỏ hơn 20 ký tự",
        ErrorTaskUrl: "Url không hợp lệ",
        ErrorTaskLoop: "Thời gian lặp không hợp lệ",
        ErrorService: "Service không hợp lệ",
        ErrorTimeUsage: "Thời gian sử dụng không hợp lệ",
        ErrorServiceNotFound: "Service không tồn tại",
        ErrorTasknameTextLength: "Độ dài của tên phải lớn hơn 3 và nhỏ hơn 30 ký tự",
        ErrorTaskLoopZeroValue: "Thời gian lặp phải có giá trị lớn hơn 0",
        ErrorServiceZeroValue: "Vui lòng chọn Service",
        ErrorTimeUsageZeroValue: "Thời gian sử dụng phải có giá trị lớn hơn 0",
        ErrorMissingTaskID: "Vui lòng nhập task ID",
        ErrorTaskNotFound: "Không tìm thấy Task",
        ErrorOldPassword: "Mật khẩu cũ không đúng",
        ErrorHasNotExpiredYet: "Yêu cầu trước đó chưa hết hiệu lực! Vui lòng thử lại sau khi hiệu lực kết thúc!",
    },
    ERROR_CHECKOUT_MESSAGES: {
        InsufficientBalance: "Tài khoản không đủ số dư",
        ErrorTaskName: "Tên không hợp lệ",
        ErrorTaskUrl: "Url không hợp lệ",
        ErrorTaskLoop: "Thời gian lặp không hợp lệ",
        ErrorService: "Service không hợp lệ",
        ErrorTimeUsage: "Thời gian sử dụng không hợp lệ",
        ErrorServiceNotFound: "Service không tồn tại",
        ErrorTasknameTextLength: "Độ dài của tên phải lớn hơn 3 và nhỏ hơn 14 ký tự",
        ErrorTaskLoopZeroValue: "Thời gian lặp phải có giá trị lớn hơn 0",
        ErrorServiceZeroValue: "Giá trị service phục vụ phải có giá trị lớn hơn 0",
        ErrorTimeUsageZeroValue: "Thời gian sử dụng phải có giá trị lớn hơn 0",
    },
    INFORMATION_ENUMS: {
        SITENAME: "NODE CRON VIP PRO",
        PRICEONETASK: 500,
    },
    ERROR_SERVER: {
        WRONG: 'Có lỗi xảy ra, vui lòng thử lại!'
    },
    ERROR_QUERY: {
        USER_NOT_FOUND: 'user not found',
    },
    ERROR_CUSTOM: {
        PASSWORD_LESS_THAN: "Mật khẩu quá ngắn!!!"
    },
    PAYMENT_MESSAGE: {
        USER_BANK_ADDED: "Thêm tài khoản ngân hàng thành công!",
        ERROR_USER_BANK_ADDED: "Thêm tài khoản ngân hàng thất bại!",
        ACCOUNT_UNIQUE_BANK_ACCOUNT: "Mỗi tài khoản chỉ có thể thêm duy nhất 1 ngân hàng!",
        MINIMUN_WITHDRAWAL_AMOUNT: "Số tiền rút tối thiểu phải lớn hơn {{amount}}!",
        BALANCE_ENOUGHT: "Số dư của bạn không đủ!",
        NOT_HAVE_SECURITY_PASSWORD: "Bạn chưa cập nhật mật khẩu bảo mật!",
        PASSWORD_SECURITY_INCORRECT: "Mật khẩu bảo mật không hợp lệ!",
        CREATE_SUCCESS_REQUEST_WITHDRAW: "Yêu cầu rút tiền thành công!",
        ERROR_CREATE_REQUEST_WITHDRAW: "Yêu cầu rút tiền thất bại!",
        NOT_TRANSACTION_BET_FOUND: "Bạn chưa có giao dịch trò chơi nào!",
        NEED_TO_PLAY_ENOUGH: "Bạn cần chơi ít nhất 3 lần cược!",
        NEED_TO_PLAY_ENOUGH_MONEY: "Bạn cần chơi ít nhất 200.000 VNĐ!"
    },
    SUCCESS: "Success",
};